[2024-07-11T15:28:58.363+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extract manual__2024-07-11T15:28:57.526833+00:00 [queued]>
[2024-07-11T15:28:58.368+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extract manual__2024-07-11T15:28:57.526833+00:00 [queued]>
[2024-07-11T15:28:58.368+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-11T15:28:58.374+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extract> on 2024-07-11 15:28:57.526833+00:00
[2024-07-11T15:28:58.377+0000] {standard_task_runner.py:57} INFO - Started process 57 to run task
[2024-07-11T15:28:58.378+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extract', 'manual__2024-07-11T15:28:57.526833+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp1z427hhr']
[2024-07-11T15:28:58.380+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask reddit_extract
[2024-07-11T15:28:58.402+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extract manual__2024-07-11T15:28:57.526833+00:00 [running]> on host d7a6ef074cc8
[2024-07-11T15:28:58.619+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Akram Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extract' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T15:28:57.526833+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T15:28:57.526833+00:00'
[2024-07-11T15:28:58.620+0000] {logging_mixin.py:151} INFO - Connected to Reddit instance
[2024-07-11T15:28:59.121+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 13, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/reddit_etls.py", line 30, in extract_posts
    post = {key: post_dict[key] for key in POST_FIELDS}
  File "/opt/airflow/etls/reddit_etls.py", line 30, in <dictcomp>
    post = {key: post_dict[key] for key in POST_FIELDS}
KeyError: 'auth'
[2024-07-11T15:28:59.129+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extract, execution_date=20240711T152857, start_date=20240711T152858, end_date=20240711T152859
[2024-07-11T15:28:59.136+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task reddit_extract ('auth'; 57)
[2024-07-11T15:28:59.182+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-11T15:28:59.194+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
