[2024-07-11T15:30:07.860+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extract manual__2024-07-11T15:30:07.097612+00:00 [queued]>
[2024-07-11T15:30:07.863+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extract manual__2024-07-11T15:30:07.097612+00:00 [queued]>
[2024-07-11T15:30:07.863+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-11T15:30:07.868+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extract> on 2024-07-11 15:30:07.097612+00:00
[2024-07-11T15:30:07.870+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2024-07-11T15:30:07.871+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extract', 'manual__2024-07-11T15:30:07.097612+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmplm6ndohx']
[2024-07-11T15:30:07.873+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask reddit_extract
[2024-07-11T15:30:07.889+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extract manual__2024-07-11T15:30:07.097612+00:00 [running]> on host d7a6ef074cc8
[2024-07-11T15:30:07.916+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Akram Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extract' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T15:30:07.097612+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T15:30:07.097612+00:00'
[2024-07-11T15:30:07.917+0000] {logging_mixin.py:151} INFO - Connected to Reddit instance
[2024-07-11T15:30:08.455+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 20, in reddit_pipeline
    load_data_to_csv(post_df, OUTPUT_PATH)
  File "/opt/airflow/etls/reddit_etls.py", line 44, in load_data_to_csv
    data.to_csv(path, index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
IsADirectoryError: [Errno 21] Is a directory: '/opt/airflow/data/output'
[2024-07-11T15:30:08.468+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extract, execution_date=20240711T153007, start_date=20240711T153007, end_date=20240711T153008
[2024-07-11T15:30:08.474+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task reddit_extract ([Errno 21] Is a directory: '/opt/airflow/data/output'; 63)
[2024-07-11T15:30:08.494+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-11T15:30:08.507+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
