[2024-07-11T15:29:24.645+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extract manual__2024-07-11T15:29:23.863455+00:00 [queued]>
[2024-07-11T15:29:24.648+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extract manual__2024-07-11T15:29:23.863455+00:00 [queued]>
[2024-07-11T15:29:24.648+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-11T15:29:24.652+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extract> on 2024-07-11 15:29:23.863455+00:00
[2024-07-11T15:29:24.655+0000] {standard_task_runner.py:57} INFO - Started process 60 to run task
[2024-07-11T15:29:24.657+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extract', 'manual__2024-07-11T15:29:23.863455+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpvcdx2tc_']
[2024-07-11T15:29:24.661+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask reddit_extract
[2024-07-11T15:29:24.680+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extract manual__2024-07-11T15:29:23.863455+00:00 [running]> on host d7a6ef074cc8
[2024-07-11T15:29:24.722+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Akram Ibrahim' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extract' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T15:29:23.863455+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T15:29:23.863455+00:00'
[2024-07-11T15:29:24.723+0000] {logging_mixin.py:151} INFO - Connected to Reddit instance
[2024-07-11T15:29:25.218+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 17, in reddit_pipeline
    post_df = transform_data(post_df)
  File "/opt/airflow/etls/reddit_etls.py", line 37, in transform_data
    post_df['over_18'] = np.where((post_df['over_18'] == True), True, False)
NameError: name 'np' is not defined
[2024-07-11T15:29:25.227+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extract, execution_date=20240711T152923, start_date=20240711T152924, end_date=20240711T152925
[2024-07-11T15:29:25.234+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task reddit_extract (name 'np' is not defined; 60)
[2024-07-11T15:29:25.263+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-11T15:29:25.273+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
